name: pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'


jobs:
  test:
    name: test repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: push sources
        run: |
          git archive --format=zip HEAD -o sources.zip
          aws s3 cp sources.zip s3://dev-pipeline-sources

